In [1]:
# This Python 3 environment comes with many helpful analytics libraries installed
# It is defined by the kaggle/python Docker image: https://github.com/kaggle/docker-python
# For example, here's several helpful packages to load

import numpy as np # linear algebra
import pandas as pd # data processing, CSV file I/O (e.g. pd.read_csv)

# Input data files are available in the read-only "../input/" directory
# For example, running this (by clicking run or pressing Shift+Enter) will list all files under the input directory

import os
for dirname, _, filenames in os.walk('/kaggle/input'):
    for filename in filenames:
        print(os.path.join(dirname, filename))

# You can write up to 20GB to the current directory (/kaggle/working/) that gets preserved as output when you create a version using "Save & Run All" 
# You can also write temporary files to /kaggle/temp/, but they won't be saved outside of the current session

In [2]:
import numpy as np

In [3]:
input_value=np.array([[0,0],[0,1],[1,1],[1,0]])
input_value.shape
input_value

array([[0, 0],
       [0, 1],
       [1, 1],
       [1, 0]])

In [4]:
output=np.array([0,1,1,1])
output=output.reshape(4,1)
output.shape

(4, 1)

In [5]:
weights=np.array([[0.2],[0.8]])
weights

array([[0.2],
       [0.8]])

In [6]:
bias=0.2

In [7]:
def sigmoid_func(x):
    return 1/(1+np.exp(-x))

In [8]:
def der(x):
    return sigmoid_func(x)*(1- sigmoid_func(x))

In [9]:
for epochs in range(15000):
    input_arr = input_value

    weighted_sum = np.dot(input_arr,weights)+bias
    first_output=sigmoid_func(weighted_sum)

    error = first_output-output
    total_error=np.square(np.subtract(first_output,output)).mean()

    first_der = error
    second_der = der(first_output)
    derivative = first_der*second_der
    
    t_input = input_value.T
    final_derivative=np.dot(t_input,derivative)
    
    weights = weights-(0.05*final_derivative)
    
    for i in derivative:
        bias = bias-(0.05*i)
print(weights)
print(bias)
    

[[7.85136211]
 [7.85231471]]
[-3.57647144]


In [10]:
pred=np.array([0,0])

result=np.dot(pred,weights)+bias

res=sigmoid_func(result)

print(res)

[0.02721297]


In [11]:
pred=np.array([1,0])

result = np.dot(pred, weights) + bias

res = sigmoid_func(result)

print(res)

[0.98627736]


In [12]:
pred=np.array([0,1])

result = np.dot(pred, weights) + bias

res = sigmoid_func(result)

print(res)

[0.98629025]


In [13]:
pred=np.array([1,1])

result = np.dot(pred, weights) + bias

res = sigmoid_func(result)

print(res)

[0.99999459]
